@startuml

!theme plain
'skinparam actorStyle hollow
left to right direction

actor Gestionnaire as G #green;line:green;line.bold;text:green
rectangle Client as C {
  :particulier: as Par
  :professionel: as Pro
}

rectangle "Green Village" {

  package Produits as P {
    C -- (consultation)
    (gestion)
  } 

  package "Panier" {
    C -- (ajout/suppression\nde produits dans panier)
    C -- (sauvegarde)
    C -- (validation)
  }

  package "Paiement" {
    Par -- (en ligne)
    Pro -- (en différé)
  }

  package "Compte" as CP {

     Par -- (création)
     C -- (modification compte)
     (modification coefficient)
     (ajout réduction sur facture)
  }
}

G -- CP
G -- P

@enduml
